<?
require_once 'inc_security.php';
//viết theo class Ajax
class MenuAjax extends AjaxCommon {
    function _loadFormAddCategory()
    {
        parent::_loadFormAddCategory(); // TODO: Change the autogenerated stub
        $array_cat = category_type($this->cat_type, 0);
        $list_cat_parent = array('' => ' -- Là danh mục cha --');
        foreach ($array_cat as $cat_i) {
            $list_cat_parent[$cat_i['cat_id']] = $cat_i['cat_name'];
        }
        $this->add(
            $this->form->text(array(
                'label' => 'Nhập tên',
                'name' => 'cat_name',
                'id' => 'cat_name',
                'require' => 1,
                'errorMsg' => 'Bạn chưa nhập danh mục nguyên liệu'
            ))
        );
        $this->add(
            $this->form->select(array(
                'label' => 'Danh mục cha',
                'name' => 'cat_parent_id',
                'id' => 'cat_parent_id',
                'option' => $list_cat_parent,
                'select' => 0
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'cat_picture',
                'id'=>'cat_picture',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img'
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'cat_note',
                'id'=>'cat_note',
                'extra'=>'style="height:120px;"'
            ))
        );
    }

    function _loadFormEditCategory()
    {
        parent::_loadFormEditCategory(); // TODO: Change the autogenerated stub
        $array_cat = category_type($this->cat_type, 0);
        $list_cat_parent = array('' => ' -- Là danh mục cha --');
        foreach ($array_cat as $cat_i) {
            $list_cat_parent[$cat_i['cat_id']] = $cat_i['cat_name'];
        }
        $this->add(
            $this->form->text(array(
                'label' => 'Nhập tên',
                'name' => 'cat_name',
                'id' => 'cat_name',
                'require' => 1,
                'errorMsg' => 'Bạn chưa nhập danh mục thực đơn',
                'value'=>$this->f['cat_name']
            ))
        );
        $this->add(
            $this->form->select(array(
                'label' => 'Danh mục cha',
                'name' => 'cat_parent_id',
                'id' => 'cat_parent_id',
                'option' => $list_cat_parent,
                'select' => $this->f['cat_parent_id']
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'cat_picture',
                'id'=>'cat_picture',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img',
                'value'=>get_picture_path($this->f['cat_picture'])
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'cat_note',
                'id'=>'cat_note',
                'extra'=>'style="height:120px;"',
                'value'=>$this->f['cat_note']
            ))
        );
    }

    function _loadFormAddRecord()
    {
        parent::_loadFormAddRecord(); // TODO: Change the autogenerated stub
        $list_cat = category_type($this->cat_type);
        $array_cat = array(' -- Chọn danh mục thực đơn -- ');
        foreach ($list_cat as $cat) {
            if (!$cat['cat_parent_id']) {
                $array_cat[$cat['cat_id']] = ' ☛ ' . $cat['cat_name'];
            }
            foreach ($list_cat as $cat_child) {
                if ($cat_child['cat_parent_id'] == $cat['cat_id']) {
                    $array_cat[$cat_child['cat_id']] = '&nbsp;&nbsp;&nbsp;&diams;&nbsp;' . $cat_child['cat_name'];
                }
            }
        }
        $array_unit = array(0=>' - Chọn đơn vị tính - ');
        $db_query = new db_query('SELECT * FROM units');
        while($row = mysqli_fetch_assoc($db_query->result)){
            $array_unit[$row['uni_id']] = $row['uni_name'];
        }
        $this->add(
            $this->form->text(array(
                'label'=>'Tên thực đơn',
                'name'=>'men_name',
                'id'=>'men_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên thực đơn'
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Đơn vị tính',
                'name'=>'men_unit_id',
                'id'=>'men_unit_id',
                'option'=>$array_unit,
                'selected'=>0,
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập đơn vị tính'
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Danh mục',
                'name'=>'men_cat_id',
                'id'=>'men_cat_id',
                'option'=>$array_cat,
                'selected'=>0,
                'require'=>1,
                'errorMsg'=>'Bạn chưa chọn danh mục thực đơn'
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=>'Giá bán chính',
                'name'=>'men_price',
                'id'=>'men_price',
                'require'=>1,
                'addon'=> 'vnđ',
                'errorMsg'=>'Bạn chưa nhập giá bán chính'
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=>'Giá bán 2',
                'name'=>'men_price1',
                'id'=>'men_price1',
                'addon'=> 'vnđ'
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=>'Giá bán 3',
                'name'=>'men_price2',
                'id'=>'men_price2',
                'addon'=> 'vnđ'
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'men_note',
                'id'=>'men_note'
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'men_image',
                'id'=>'men_image',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img'
            ))
        );
    }

    function _loadFormEditRecord()
    {
        parent::_loadFormEditRecord(); // TODO: Change the autogenerated stub
        $list_cat = category_type($this->cat_type);
        $array_cat = array(' -- Chọn danh mục thực đơn -- ');
        foreach ($list_cat as $cat) {
            if (!$cat['cat_parent_id']) {
                $array_cat[$cat['cat_id']] = ' ☛ ' . $cat['cat_name'];
            }
            foreach ($list_cat as $cat_child) {
                if ($cat_child['cat_parent_id'] == $cat['cat_id']) {
                    $array_cat[$cat_child['cat_id']] = '&nbsp;&nbsp;&nbsp;&diams;&nbsp;' . $cat_child['cat_name'];
                }
            }
        }
        $array_unit = array(0=>' - Chọn đơn vị tính - ');
        $db_query = new db_query('SELECT * FROM units');
        while($row = mysqli_fetch_assoc($db_query->result)){
            $array_unit[$row['uni_id']] = $row['uni_name'];
        }
        $this->add(
            $this->form->text(array(
                'label'=>'Tên thực đơn',
                'name'=>'men_name',
                'id'=>'men_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên thực đơn',
                'value'=>$this->f['men_name']
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Đơn vị tính',
                'name'=>'men_unit_id',
                'id'=>'men_unit_id',
                'option'=>$array_unit,
                'selected'=>$this->f['men_unit_id'],
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập đơn vị tính'
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Danh mục',
                'name'=>'men_cat_id',
                'id'=>'men_cat_id',
                'option'=>$array_cat,
                'selected'=>$this->f['men_cat_id'],
                'require'=>1,
                'errorMsg'=>'Bạn chưa chọn danh mục thực đơn'
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=>'Giá bán chính',
                'name'=>'men_price',
                'id'=>'men_price',
                'require'=>1,
                'addon'=> 'vnđ',
                'errorMsg'=>'Bạn chưa nhập giá bán chính',
                'value'=>$this->f['men_price']
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=>'Giá bán 2',
                'name'=>'men_price1',
                'id'=>'men_price1',
                'addon'=> 'vnđ',
                'value'=>$this->f['men_price1']
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=>'Giá bán 3',
                'name'=>'men_price2',
                'id'=>'men_price2',
                'addon'=> 'vnđ',
                'value'=>$this->f['men_price2']
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'men_note',
                'id'=>'men_note',
                'value'=>$this->f['men_note']
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'men_image',
                'id'=>'men_image',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img',
                'value'=>get_picture_path($this->f['men_image'])
            ))
        );
    }

    function _listAdd()
    {
        $this->list->add('men_id','Mã');
        $this->list->add('men_name','Tên thực đơn','string',1,1);
        $this->list->add('men_unit_id','Đơn vị tính','string',0,0);
        $this->list->add('men_price','Giá bán');
        $this->list->add('','SL tồn');
    }

    function _listColumn($row = array())
    {
        global $array_unit;
        $list_column = '';
        $list_column .= '<td class="center">'.$row['men_id'].'</td>';
        $list_column .= '<td class="center">'.$row['men_name'].'</td>';
        $list_column .= '<td class="center">' . $array_unit[$row['men_unit_id']] . '</td>';
        $list_column .= '<td class="center">'.format_number($row['men_price']).' vnđ</td>';
        $list_column .= '<td class="center">'.'</td>';
        return $list_column;
    }


    //load chi tiết thực đơn
    function loadMenuDetail() {
        //contextmenuclass cho phần chi tiết thực đơn
        $class_context_menu = '';
        $record_id = getValue('record_id','int','POST','');
        $table = 'menu_products';
        $html = '';
        //Thêm hidden menu_id để gửi trong form công thức chế biến
        $html .= $this->form->hidden(array('name'=>'selected_menu','id'=>'selected_menu','value'=>$record_id));
        $this->list->add('','Nguyên liệu');
        $this->list->add('','SL');
        $this->list->add('','ĐVT');
        $db_count = new db_count('SELECT count(*) as count
                                  FROM '.$table.'
                                  WHERE mep_menu_id = '.$record_id . $this->list->sqlSearch());
        $total = $db_count->total; unset($db_count);
        $sql = 'SELECT *
                FROM '.$table.'
                LEFT JOIN products ON pro_id = mep_product_id
                LEFT JOIN units ON uni_id = pro_unit_id
                WHERE mep_menu_id = '.$record_id. $this->list->sqlSearch() .'
                ORDER BY '.$this->list->sqlSort().' pro_name ASC
                '.$this->list->limit($total);
        $db_listing = new db_query($sql);
        $array_row = $db_listing->resultArray();unset($db_listing);
        $total_row = count($array_row);
        $html .= $this->list->showHeader($total_row,'','id="menu_product_listing"');
        $i = 0;
        foreach($array_row as $row){
            $i++;
            $html .= $this->list->start_tr($i,'product_'.$row['pro_id'],'class="'.$class_context_menu.' menu-product-item" onclick="active_menu_product('.$row['pro_id'].')" data-record_id="'.$row['pro_id'].'" data-menu_id = "'.$record_id.'"');
            $html .= '<td>'.$row['pro_name'].'</td>';
            $html .= '<td>'.$row['mep_quantity'].'</td>';
            $html .= '<td>'.$row['uni_name'].'</td>';
            $html .= $this->list->end_tr();
        }
        $html .= $this->list->showFooter();
        $html .='<div class="pos_bottom alert-warning text-left">
    <label>Lưu ý:</label>
    <br/>
    Định lượng nguyên liệu của một thực đơn dựa vào số lượng chế biến của nguyên liệu( chính là mặt hàng trong kho hàng). Nếu bạn muốn quản lý kho hàng và các mặt hàng
    được tự động trừ khi phục vụ thực đơn. Bạn phải tạo định lượng theo số lượng tương ứng.
    <br/>
    Với các mặt hàng không phải chế biến, có nghĩa là nhập về có thể bán được ngay(vd: bia, nước ngọt ...) thì bạn cũng phải tạo định lượng chế biến là 1 để khi bán hàng kho hàng tự động trừ tương ứng
        <label>Số lượng tồn của thực đơn</label>
        được tính toán dựa trên công thức chế biến của thực đơn đó và số lượng tồn của các nguyên liệu trong kho hàng.
</div>';
        $this->add($html);
    }

    //Form thêm mới nguyên liệu vào thực đơn
    function loadFormAddMenuProduct() {
        //Kiểm tra quyền
        checkCustomPermission('CONG_THUC_CHE_BIEN');
        //lấy ra id thực đơn
        $menu_id = getValue('menu','int','POST','');
        //open modal
        $this->openModal();
        //...add more and morestring
        //lấy ra danh sách nguyên liệu đang có
        $db_query = new db_query('SELECT *
                                  FROM products
                                  LEFT JOIN units ON uni_id = pro_unit_id
                                  ORDER BY pro_name ASC
                                  LIMIT 100');
        $list_product = array(' -- Chọn nguyên liệu -- ');
        $list_unit = array();
        while($row = mysqli_fetch_assoc($db_query->result)) {
            $list_product[$row['pro_id']] = $row['pro_name'];
            $list_unit[$row['pro_id']] = $row['uni_name'];
        }
        $this->add(
            $this->form->hidden(array(
                'name'=>'mep_menu_id',
                'id'=>'mep_menu_id',
                'value'=>$menu_id
            ))
        );
        $this->add(
            $this->form->select(array(
                'label' => 'Chọn nguyên liệu',
                'name'=>'mep_product_id',
                'id'=>'mep_product_id',
                'option'=>$list_product,
                'extra'=>'onchange="getProductUnit()"',
                'require'=>1,
                'errorMsg'=>'Bạn chưa chọn nguyên liệu'
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=> 'Số lượng',
                'name'=>'mep_quantity',
                'id'=>'mep_quantity',
                'addon'=>'đvt'
            ))
        );
        $this->add(
            '<script type="text/javascript">
                var list_unit = '.json_encode($list_unit).';
            </script>'
        );
        //...
        //close modal
        $this->closeModal('add_menu_product');
    }

    //Form thêm mới nguyên liệu vào thực đơn
    function loadFormEditMenuProduct() {
        //Kiểm tra quyền
        checkCustomPermission('CONG_THUC_CHE_BIEN');
        //lấy ra id thực đơn
        $menu_id = getValue('menu','int','POST',0);
        //lấy ra id của nguyên liệu
        $record_id = getValue('record_id','int','POST',0);
        //open modal
        $this->openModal();
        //...add more and morestring
        //lấy chi tiết nguyên liệu
        $db_query = new db_query('SELECT pro_name, uni_name, mep_quantity
                                  FROM menu_products
                                  LEFT JOIN products ON mep_product_id = pro_id
                                  LEFT JOIN units ON uni_id = pro_unit_id
                                  WHERE pro_id = ' .$record_id.'
                                  AND mep_menu_id = '.$menu_id.'
                                  LIMIT 1');
        $row = mysqli_fetch_assoc($db_query->result);unset($db_query);
        $this->add(
            $this->form->hidden(array(
                'name'=>'mep_menu_id',
                'id'=>'mep_menu_id',
                'value'=>$menu_id
            ))
        );
        $this->add(
            $this->form->hidden(array(
                'name'=>'mep_product_id',
                'id'=>'mep_product_id',
                'value'=>$record_id
            ))
        );
        $this->add(
            $this->form->staticInput(array(
                'label'=>'Nguyên liệu',
                'value'=>$row['pro_name']
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=> 'Số lượng',
                'name'=>'mep_quantity',
                'id'=>'mep_quantity',
                'addon'=>$row['uni_name'],
                'value'=>$row['mep_quantity']
            ))
        );
        //...
        //close modal
        $this->closeModal('edit_menu_product');
    }
    // delete cong thuc che bien
    function deleteMenuProduct()
    {
        checkPermission('trash');
        $array_return = array();
        $mep_pro_id = getValue('record_id','int','POST',0);
        $men_id = getValue('men_id','int','POST',0);
        if ( !$mep_pro_id || !$men_id )
        {
            $array_return['success'] = 0;
            echo json_encode($array_return);
            exit();
        }
        $db_mep_pro = new db_query('SELECT * FROM menu_products 
                                    WHERE mep_menu_id = ' . $men_id . ' 
                                    AND mep_product_id = ' . $mep_pro_id );
        $data_mep_pro = mysqli_fetch_assoc($db_mep_pro->result); unset($db_mep_pro);
        if ( $data_mep_pro )
        {
            $db_delete = new db_execute('DELETE FROM menu_products WHERE 1 
                                         AND mep_menu_id = ' . $men_id . ' 
                                         AND mep_product_id = ' . $mep_pro_id); 
            unset($db_delete);
            $array_return['success'] = 1; 
        }
        else{
            exit();
        }
        echo json_encode($array_return);
    }
    
}
// khai bao cac bien global
$array_unit = array();
$db_query = new db_query('SELECT * FROM units');
while($row = mysqli_fetch_assoc($db_query->result)){
    $array_unit[$row['uni_id']] = $row['uni_name'];
}
// khoi tao doi tuong object ajax va thuc thi
$menuajax = new MenuAjax();
$menuajax->execute();
