<?
require_once 'inc_security.php';
//class Ajax - version 1.0
class Store_listAjax extends AjaxCommon {
    function _loadFormAddRecord()
    {
        parent::_loadFormAddRecord(); // TODO: Change the autogenerated stub
        $this->add(
            $this->form->text(array(
                'label'=>'Nhập tên',
                'name'=>'cat_name',
                'id'=>'cat_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập lý do'
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'cat_picture',
                'id'=>'cat_picture',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img'
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'cat_note',
                'id'=>'cat_note'
            ))
        );
    }

    function _loadFormEditRecord()
    {
        parent::_loadFormEditRecord(); // TODO: Change the autogenerated stub
        $this->add(
            $this->form->text(array(
                'label'=>'Nhập tên',
                'name'=>'cat_name',
                'id'=>'cat_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập lý do',
                'value'=>$this->f['cat_name']
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'cat_picture',
                'id'=>'cat_picture',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img',
                'value'=>get_picture_path($this->f['cat_picture'])
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'cat_note',
                'id'=>'cat_note',
                'value'=>$this->f['cat_note']
            ))
        );
    }


}
$storeajax = new Store_listAjax();
$storeajax->execute();
