<?
require_once 'inc_security.php';
//class Ajax - version 1.0
class FinsAjax extends AjaxCommon {
    function _loadFormAddRecord()
    {
        parent::_loadFormAddRecord(); // TODO: Change the autogenerated stub
        global $cat_type_in, $cat_type_out;
        $this->add(
            $this->form->text(array(
                'label'=>'Nhập tên',
                'name'=>'cat_name',
                'id'=>'cat_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập lý do'
            ))
        );
        $this->add(
            $this->form->list_radio(array(
                'label' => 'Loại lý do',
                'list'=>array(
                    array(
                        'label'=>'Lý do thu',
                        'name'=>'cat_type',
                        'id'=>'money_in',
                        'value'=>$cat_type_in,
                        'is_check'=>0
                    ),
                    array(
                        'label'=>'Lý do chi',
                        'name'=>'cat_type',
                        'id'=>'money_out',
                        'value'=>$cat_type_out,
                        'is_check'=>1
                    ),
                ),
                'column'=>2
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'cat_picture',
                'id'=>'cat_picture',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img'
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'cat_note',
                'id'=>'cat_note'
            ))
        );
    }

    function _loadFormEditRecord()
    {
        parent::_loadFormEditRecord(); // TODO: Change the autogenerated stub
        global $cat_type_in, $cat_type_out;
        $this->add(
            $this->form->text(array(
                'label'=>'Nhập tên',
                'name'=>'cat_name',
                'id'=>'cat_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập lý do',
                'value'=>$this->f['cat_name']
            ))
        );
        $this->add(
            $this->form->list_radio(array(
                'label' => 'Loại lý do',
                'list'=>array(
                    array(
                        'label'=>'Lý do thu',
                        'name'=>'cat_type',
                        'id'=>'money_in',
                        'value'=>$cat_type_in,
                        'is_check'=>0
                    ),
                    array(
                        'label'=>'Lý do chi',
                        'name'=>'cat_type',
                        'id'=>'money_out',
                        'value'=>$cat_type_out,
                        'is_check'=>1
                    ),
                ),
                'column'=>2
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'cat_picture',
                'id'=>'cat_picture',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img',
                'value'=>get_picture_path($this->f['cat_picture'])
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'cat_note',
                'id'=>'cat_note',
                'value'=>$this->f['cat_note']
            ))
        );
    }


}
$menuajax = new FinsAjax();
$menuajax->execute();
