<?
require_once 'inc_security.php';
//class Ajax - version 1.0
class SuppliersAjax extends AjaxCommon {
    function _loadFormAddCategory()
    {
        parent::_loadFormAddCategory(); // TODO: Change the autogenerated stub
        $this->add(
            $this->form->text(array(
                'label'=>'Nhập tên',
                'name'=>'cat_name',
                'id'=>'cat_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên nhóm nhà cung cấp'
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'cat_picture',
                'id'=>'cat_picture',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img'
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'cat_note',
                'id'=>'cat_note'
            ))
        );
    }

    function _loadFormEditCategory()
    {
        parent::_loadFormEditCategory(); // TODO: Change the autogenerated stub
        $this->add(
            $this->form->text(array(
                'label'=>'Nhập tên',
                'name'=>'cat_name',
                'id'=>'cat_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên nhóm nhà cung cấp',
                'value'=>$this->f['cat_name']
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'cat_picture',
                'id'=>'cat_picture',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img',
                'value'=>$this->f['cat_picture']
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'cat_note',
                'id'=>'cat_note',
                'value'=>$this->f['cat_note']
            ))
        );
        }

    function _loadFormAddRecord()
    {
        parent::_loadFormAddRecord(); // TODO: Change the autogenerated stub
        //lấy list category
        $list_cat = category_type($this->cat_type);
        $array_cat = array(''=>' -- Chọn nhóm nhà cung cấp -- ');
        foreach($list_cat as $cat){
            $array_cat[$cat['cat_id']] = $cat['cat_name'];
        }
        $this->add(
            $this->form->text(array(
                'label'=>'Tên nhà cung cấp',
                'name'=>'sup_name',
                'id'=>'sup_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên nhà cung cấp'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Địa chỉ',
                'name'=>'sup_address',
                'id'=>'sup_address',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập địa chỉ nhà cung cấp'
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'sup_image',
                'id'=>'sup_image',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img'
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Nhóm',
                'name'=>'sup_cat_id',
                'id'=>'sup_cat_id',
                'option'=>$array_cat,
                'selected'=>0,
                'require'=>1,
                'errorMsg'=>'Bạn chưa chọn nhóm nhà cung cấp'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Điện thoại',
                'name'=>'sup_phone',
                'id'=>'sup_phone'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Di động',
                'name'=>'sup_mobile',
                'id'=>'sup_mobile'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Fax',
                'name'=>'sup_fax',
                'id'=>'sup_fax'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Email',
                'name'=>'sup_email',
                'id'=>'sup_email'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Website',
                'name'=>'sup_website',
                'id'=>'sup_website'
            ))
        );
    }

    function _loadFormEditRecord()
    {
        parent::_loadFormEditRecord(); // TODO: Change the autogenerated stub
        $list_cat = category_type($this->cat_type);
        $array_cat = array(''=>' -- Chọn nhóm nhà cung cấp -- ');
        foreach($list_cat as $cat){
            $array_cat[$cat['cat_id']] = $cat['cat_name'];
        }
        $this->add(
            $this->form->text(array(
                'label'=>'Tên nhà cung cấp',
                'name'=>'sup_name',
                'id'=>'sup_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên nhà cung cấp',
                'value'=>$this->f['sup_name']
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Địa chỉ',
                'name'=>'sup_address',
                'id'=>'sup_address',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập địa chỉ nhà cung cấp',
                'value'=>$this->f['sup_address']
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'sup_image',
                'id'=>'sup_image',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img',
                'value'=>get_picture_path($this->f['sup_image'])
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Nhóm',
                'name'=>'sup_cat_id',
                'id'=>'sup_cat_id',
                'option'=>$array_cat,
                'selected'=>$this->f['sup_cat_id'],
                'require'=>1,
                'errorMsg'=>'Bạn chưa chọn nhóm nhà cung cấp'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Điện thoại',
                'name'=>'sup_phone',
                'id'=>'sup_phone',
                'value'=>$this->f['sup_phone']
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Di động',
                'name'=>'sup_mobile',
                'id'=>'sup_mobile',
                'value'=>$this->f['sup_mobile']
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Fax',
                'name'=>'sup_fax',
                'id'=>'sup_fax',
                'value'=>$this->f['sup_fax']
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Email',
                'name'=>'sup_email',
                'id'=>'sup_email',
                'value'=>$this->f['sup_email']
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Website',
                'name'=>'sup_website',
                'id'=>'sup_website',
                'value'=>$this->f['sup_website']
            ))
        );
    }
    function _listAdd()
    {
        $this->list->add('sup_name','Tên NCC');
        $this->list->add('sup_phone','Số ĐT');
        $this->list->add('sup_address','Địa chỉ');
    }

    function _listColumn($row = array())
    {
        global $array_unit;
        $list_column = '';
        $list_column .= '<td class="center">' . $row['sup_name'] . '</td>';
        $list_column .= '<td class="center">' . $row['sup_address'] . '</td>';
        $list_column .= '<td class="center">' . $row['sup_phone'].'</td>';
        return $list_column;
    }
}
$supplierajax = new SuppliersAjax();
$supplierajax->execute();
