<?
require_once 'inc_security.php';
//viết theo class Ajax
class CustomerAjax extends AjaxCommon {
    function _loadFormAddCategory()
    {
        parent::_loadFormAddCategory(); // TODO: Change the autogenerated stub
        $this->add(
            $this->form->text(array(
                'label'=>'Nhập tên',
                'name'=>'cat_name',
                'id'=>'cat_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên nhóm nhân viên'
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'cat_picture',
                'id'=>'cat_picture',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img'
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'cat_note',
                'id'=>'cat_note'
            ))
        );
    }

    function _loadFormEditCategory()
    {
        parent::_loadFormEditCategory(); // TODO: Change the autogenerated stub
        $this->add(
            $this->form->text(array(
                'label'=>'Nhập tên',
                'name'=>'cat_name',
                'id'=>'cat_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên nhóm nhân viên',
                'value'=>$this->f['cat_name']
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'cat_picture',
                'id'=>'cat_picture',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img',
                'value'=>$this->f['cat_picture']
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'cat_note',
                'id'=>'cat_note',
                'value'=>$this->f['cat_note']
            ))
        );
    }

    function _loadFormAddRecord()
    {
        parent::_loadFormAddRecord(); // TODO: Change the autogenerated stub
        global $configuration;
        $list_cat = category_type($this->cat_type);
        $array_cat = array('' => ' -- Chọn nhóm nhân viên -- ');
        foreach($list_cat as $cat){
            $array_cat[$cat['cat_id']] = $cat['cat_name'];
        }
        $db_age = new db_query('SELECT * FROM agencies');
        $list_agencies = array();
        while($row = mysqli_fetch_assoc($db_age->result)) {
            $list_agencies[$row['age_id']] = $row['age_name'];
        }
        unset($db_query);
        $this->add(
            $this->form->text(array(
                'label'=>'Tên nhân viên',
                'name'=>'use_name',
                'id'=>'use_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên nhân viên'
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Thuộc cửa hàng',
                'name'=>'use_agency_id',
                'id'=>'use_agency_id',
                'option'=>$list_agencies,
                'selected'=>$configuration['con_default_agency'],
                'require'=>1,
                'errorMsg'=>'Bạn chưa chọn cửa hàng'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Địa chỉ',
                'name'=>'use_address',
                'id' => 'use_address',
                'require' => 1,
                'errorMsg' => 'Bạn chưa nhập địa chỉ'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Điện thoại',
                'name'=>'use_phone',
                'id'=>'use_phone'
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=>'Lương ca',
                'name'=>'use_pay',
                'id'=>'use_pay',
                'addon'=>'vnđ'
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=>'Chiết khấu',
                'name'=>'use_discount',
                'id'=>'use_discount',
                'addon'=>'%'
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Nhóm nhân viên',
                'name'=>'use_group_id',
                'id'=>'use_group_id',
                'option'=>$array_cat,
                'require' => 1,
                'errorMsg' => 'Bạn chưa chọn nhóm nhân viên'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Mã nhân viên tự nhập',
                'name'=>'use_code',
                'id'=>'use_code'
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'use_note',
                'id'=>'use_note'
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'use_image',
                'id'=>'use_image',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img'
            ))
        );
    }

    function _loadFormEditRecord()
    {
        $list_cat = category_type($this->cat_type);
        $array_cat = array('' => ' -- Chọn nhóm nhân viên -- ');
        foreach($list_cat as $cat){
            $array_cat[$cat['cat_id']] = $cat['cat_name'];
        }
        unset($db_query);
        parent::_loadFormEditRecord(); // TODO: Change the autogenerated stub
        $db_age = new db_query('SELECT * FROM agencies');
        $list_agencies = array();
        while($row = mysqli_fetch_assoc($db_age->result)) {
            $list_agencies[$row['age_id']] = $row['age_name'];
        }
        $this->add(
            $this->form->text(array(
                'label'=>'Tên nhân viên',
                'name'=>'use_name',
                'id'=>'use_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên nhân viên',
                'value'=>$this->f['use_name']
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Thuộc cửa hàng',
                'name'=>'use_agency_id',
                'id'=>'use_agency_id',
                'option'=>$list_agencies,
                'selected'=>$this->f['use_agency_id'],
                'require'=>1,
                'errorMsg'=>'Bạn chưa chọn cửa hàng'
            ))
        );

        $this->add(
            $this->form->text(array(
                'label'=>'Địa chỉ',
                'name'=>'use_address',
                'id' => 'use_address',
                'require' => 1,
                'errorMsg' => 'Bạn chưa nhập địa chỉ',
                'value'=>$this->f['use_address']
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Điện thoại',
                'name'=>'use_phone',
                'id'=>'use_phone',
                'value'=>$this->f['use_phone']
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=>'Lương ca',
                'name'=>'use_pay',
                'id'=>'use_pay',
                'addon'=>'vnđ',
                'value'=>$this->f['use_pay']
            ))
        );
        $this->add(
            $this->form->number(array(
                'label'=>'Chiết khấu',
                'name'=>'use_discount',
                'id'=>'use_discount',
                'addon'=>'%',
                'value'=>$this->f['use_discount']
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Nhóm nhân viên',
                'name'=>'use_group_id',
                'id'=>'use_group_id',
                'option'=>$array_cat,
                'selected'=>$this->f['use_group_id'],
                'require' => 1,
                'errorMsg' => 'Bạn chưa chọn nhóm nhân viên'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Mã nhân viên tự nhập',
                'name'=>'use_code',
                'id'=>'use_code',
                'value'=>$this->f['use_code']
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'use_note',
                'id'=>'use_note',
                'value'=>$this->f['use_note']
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'use_image',
                'id'=>'use_image',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img',
                'value'=>get_picture_path($this->f['use_image'])
            ))
        );

    }

    function changePassword(){

        $array_return = array();
        $admin_id   = getValue('adm_id','int','POST',0);
        $pass_old   = getValue('pass_old','str','POST','');
        $pass_new   = getValue('pass_new','str','POST','');
        $repass_new = getValue('repass_new','str','POST','');
        if(!$pass_old){
            $array_return = array('error' => 'Bạn chưa điền mật khẩu cũ');
            die(json_encode($array_return));
        }
        if(!$pass_new || !$repass_new || $repass_new != $pass_new){
            $array_return = array('error' => 'Mật khẩu mới không hợp lệ');
            die(json_encode($array_return));
        }
        $db_admin_pas = new db_query('SELECT adm_password FROM admin_users WHERE adm_id = '.$admin_id.'');
        $row_admin_pas = mysqli_fetch_assoc($db_admin_pas->result); unset($db_admin_pas);
        if($row_admin_pas['adm_password'] != md5($pass_old)){
            $array_return = array('error' => 'Mật khẩu cũ không đúng');
            die(json_encode($array_return));
        } else {
            $db_update_pass = new db_execute('UPDATE admin_users SET adm_password = "'.md5($pass_new).'" WHERE adm_id = '.$admin_id.'');
            if($db_update_pass->total){
                $array_return = array('success' => 1, 'msg' => 'Đổi mật khẩu thành công');
                die(json_encode($array_return));
            } else {
                $array_return = array('error' => 'Đổi mật khẩu thành công');
                die(json_encode($array_return));
            }
        }
    }

    function _listAdd()
    {

        $this->list->add('use_id','Mã hệ thống');
        $this->list->add('use_code','Mã có sẵn');
        $this->list->add('use_name','Tên nhân viên','string',1,1);
        $this->list->add('use_address','Địa chỉ');
        $this->list->add('use_phone','Điện thoại');
        $this->list->add('use_note','Ghi chú');
    }

    function _listColumn($row = array())
    {
        $list_column = '';
        $list_column .= '<td class="center">'.$row['use_id'].'</td>';
        $list_column .= '<td class="center">'.$row['use_code'].'</td>';
        $list_column .= '<td class="center">'.$row['use_name'].'</td>';
        $list_column .= '<td class="center">'.$row['use_address'].'</td>';
        $list_column .= '<td class="center">'.$row['use_phone'].'</td>';
        $list_column .= '<td class="center">'.$row['use_note'].'</td>';
        return $list_column;
    }
}
// khoi tao doi tuong object ajax va thuc thi
$customerajax = new CustomerAjax();
$customerajax->execute();
