<?
require_once 'inc_security.php';
//viết theo class Ajax
class AgenciesAjax extends AjaxCommon {
    function loadFormEditCategory() {
        // TODO: Implement loadFormEditCategory() method.
        //kiểm tra quyền edit
        checkPermission('edit');
        //lấy ra cat_id cần chỉnh sửa
        $cat_id = getValue('cat_id','int','POST',0);
        //lấy ra data cat id
        $db_data = new db_query('SELECT * FROM '.$this->cat_table . ' WHERE age_id = ' . $cat_id);

        if($row = mysqli_fetch_assoc($db_data->result)){
            //extract($row);
            $this->f = $row;
        }else{
            exit();
        }
        //open modal
        $this->openModal();
        //...add more and morestring
        $this->_loadFormEditCategory();
        //...
        //close modal
        $this->closeModal('edit_category',$cat_id);
    }
    function _loadFormAddCategory()
    {
        parent::_loadFormAddCategory(); // TODO: Change the autogenerated stub
        $this->add(
            $this->form->text(array(
                'label'=>'Nhập tên',
                'name'=>'age_name',
                'id'=>'age_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên cửa hàng'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Địa chỉ',
                'name'=>'age_address',
                'id'=>'age_address',
                'require'=>1,
                'errorMsg'=> 'Bạn chưa nhập địa chỉ'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Điện thoại',
                'name'=>'age_phone',
                'id'=>'age_phone',
                'require' => 1,
                'errorMsg' => 'Bạn chưa nhập điện thoại'
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'age_image',
                'id'=>'age_image',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img'
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'age_note',
                'id'=>'age_note'
            ))
        );
    }
    function _loadFormEditCategory()
    {
        parent::_loadFormEditCategory(); // TODO: Change the autogenerated stub
        //kiểm tra quyền edit
        checkPermission('edit');
        global $cat_table;
        //lấy ra cat_id cần chỉnh sửa
        $cat_id = getValue('cat_id','int','POST',0);
        //lấy ra data cat id
        $db_data = new db_query('SELECT * FROM '.$cat_table.' WHERE age_id = '.$cat_id.' LIMIT 1');
        if($row = mysqli_fetch_assoc($db_data->result)){
            extract($row);
        }else{
            exit();
        }
        $this->add(
            $this->form->text(array(
                'label'=>'Nhập tên',
                'name'=>'age_name',
                'id'=>'age_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên nhóm khách hàng',
                'value'=>$this->f['age_name']
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Địa chỉ',
                'name'=>'age_address',
                'id'=>'age_address',
                'value'=>$this->f['age_address']
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Điện thoại',
                'name'=>'age_phone',
                'id'=>'age_phone',
                'value'=>$this->f['age_phone']
            ))
        );
        $this->add(
            $this->form->ajaxUploadFile(array(
                'label'=>'Ảnh đại diện',
                'name'=>'age_image',
                'id'=>'age_image',
                'browse_id'=>'browse_img',
                'viewer_id'=>'viewer_img',
                'value'=>get_picture_path($this->f['age_image'])
            ))
        );
        $this->add(
            $this->form->textarea(array(
                'label'=>'Ghi chú',
                'name'=>'age_note',
                'id'=>'age_note',
                'value'=>$this->f['age_note']
            ))
        );
    }
    function deleteCategory(){
        //kiểm tra quyền xóa
        global $cat_table;
        checkPermission('trash');
        $cat_id = getValue('cat_id','int','POST',0);
        $db_data = new db_query('SELECT * FROM '.$cat_table.' WHERE age_id = '.$cat_id .' LIMIT 1');
        $array_data = mysqli_fetch_assoc($db_data->result);unset($db_data);
        if($array_data){
            move2trash('age_id',$cat_id,$cat_table,$array_data);
            $array_return = array('success'=>1);
        }else{
            exit();
        }
        die(json_encode($array_return));
    }

    function _loadFormAddRecord()
    {
        parent::_loadFormAddRecord(); // TODO: Change the autogenerated stub
        //kiểm tra quyền add
        checkPermission('add');
        global $cat_table;
        //lấy ra danh sách các cửa hàng
        $list_agencies = array(''=> ' -- Chọn cửa hàng -- ');
        $db_agen = new db_query('SELECT * FROM '.$cat_table.'');
        while($row = mysqli_fetch_assoc($db_agen->result)){
            $list_agencies[$row['age_id']] = $row['age_name'];
        }
        unset($db_agen);
        $this->add(
            $this->form->text(array(
                'label'=>'Tên quầy phục vụ',
                'name'=>'sed_name',
                'id'=>'sed_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên quầy phục vụ'
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Điện thoại',
                'name'=>'sed_phone',
                'id' => 'sed_phone'
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Cửa hàng',
                'name'=>'sed_agency_id',
                'id'=>'sed_agency_id',
                'selected'=>0,
                'require'=>1,
                'errorMsg'=>'Bạn chưa chọn cửa hàng',
                'option'=>$list_agencies
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Ghi chú',
                'name'=>'sed_note',
                'id'=>'sed_note'

            ))
        );
    }
    function _loadFormEditRecord()
    {
        parent::_loadFormEditRecord(); // TODO: Change the autogenerated stub
        //kiểm tra quyền edit
        checkPermission('edit');
        global $cat_table;
        global $bg_table;
        global $id_field;
        $record_id = getValue('record_id','int','POST',0);
        //lấy ra danh sách các cửa hàng
        $list_agencies = array(''=> ' -- Chọn cửa hàng -- ');
        $db_agen = new db_query('SELECT * FROM '.$cat_table);
        while($row = mysqli_fetch_assoc($db_agen->result)){
            $list_agencies[$row['age_id']] = $row['age_name'];
        }
        unset($db_agen);
        //lấy ra data cat id
        $db_data = new db_query('SELECT * FROM '.$bg_table.' WHERE '.$id_field.' = '.$record_id.' LIMIT 1');
        if($row = mysqli_fetch_assoc($db_data->result)){
            extract($row);
        }else{
            exit();
        }
        $this->add(
            $this->form->text(array(
                'label'=>'Tên quầy phục vụ',
                'name'=>'sed_name',
                'id'=>'sed_name',
                'require'=>1,
                'errorMsg'=>'Bạn chưa nhập tên quầy phục vụ',
                'value'=>$this->f['sed_name']
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Điện thoại',
                'name'=>'sed_phone',
                'id' => 'sed_phone',
                'value'=>$this->f['sed_phone']
            ))
        );
        $this->add(
            $this->form->select(array(
                'label'=>'Cửa hàng',
                'name'=>'sed_agency_id',
                'id'=>'sed_agency_id',
                'selected'=>$this->f['sed_agency_id'],
                'require'=>1,
                'errorMsg'=>'Bạn chưa chọn cửa hàng',
                'option'=>$list_agencies
            ))
        );
        $this->add(
            $this->form->text(array(
                'label'=>'Ghi chú',
                'name'=>'sed_note',
                'id'=>'sed_note',
                'value'=> $this->f['sed_note']
            ))
        );

    }
    function deleteRecord(){
        //kiểm tra quyền xóa
        checkPermission('trash');
        global $bg_table;
        global $id_field;
        $record_id = getValue('record_id','int','POST',0);
        $db_data = new db_query('SELECT * FROM '.$bg_table.' WHERE '.$id_field.' = '.$record_id .' LIMIT 1');
        $array_data = mysqli_fetch_assoc($db_data->result);unset($db_data);
        if($array_data){
            move2trash($id_field,$record_id,$bg_table,$array_data);
            $array_return = array('success'=>1);
        }else{
            exit();
        }
        die(json_encode($array_return));
    }
    function recoveryRecord(){
        //kiểm tra quyền khôi phục
        checkPermission('recovery');
        global $bg_table;
        $record_id = getValue('record_id','int','POST',0);
        //phục hồi dữ liệu
        $result = trash_recovery($record_id,$bg_table);
        if($result){
            $array_return = array('success'=>1);
        }else{
            $array_return = array('success'=>0,'error'=>'Khôi phục không thành công');
        }
        die(json_encode($array_return));
    }
    function terminalDeleteRecord(){
        //kiểm tra quyền xóa vĩnh viễn
        global $bg_table;
        checkPermission('delete');
        $record_id = getValue('record_id','int','POST',0);
        //xóa hoàn toàn
        terminal_delete($record_id,$bg_table);
        $array_return = array('success'=>1);
        die(json_encode($array_return));
    }
    function listRecord(){
        global $id_field;
        global $bg_table;
        global $cat_field;
        $cat_id = getValue('cat_id','str','POST',0);
        $html = '';
        $class_context_menu = 'menu-normal';
        #Bắt đầu với datagrid
        $list = new dataGrid($id_field,30);
        /*code something*/
        $list->add('','Tên cửa hàng');
        $list->add('','Điện thoại');
        switch($cat_id){
            case 'all':
                $db_count = new db_count('SELECT count(*) as count
                                          FROM '.$bg_table.'
                                          WHERE 1 '.$list->sqlSearch());
                $total = $db_count->total;unset($db_count);
                $db_listing = new db_query('SELECT *
                            FROM '.$bg_table.'
                            WHERE 1 '.$list->sqlSearch().'
                            ORDER BY '.$list->sqlSort().' '.$id_field.' ASC
                            '.$list->limit($total));
                $array_row = $db_listing->resultArray();unset($db_listing);
                break;
            case 'trash':
                $class_context_menu = 'menu-trash';
                $db_count = new db_count('SELECT count(*) as count
                            FROM trash
                            WHERE tra_table = "'.$bg_table.'"');
                $total = $db_count->total;unset($db_count);
                $array_row = trash_list($bg_table);
                $list->limit($total);
                break;
            default :
                $cat_id = (int)$cat_id;
                $db_count = new db_count('SELECT count(*) as count
                                          FROM '.$bg_table.'
                                          WHERE 1 '.$list->sqlSearch() .'
                                          AND '.$cat_field.' = '. $cat_id);
                $total = $db_count->total;unset($db_count);
                $db_listing = new db_query('SELECT *
                                            FROM '.$bg_table.'
                                            WHERE 1 '.$list->sqlSearch().'
                                            AND '.$cat_field.' = '. $cat_id.'
                                            ORDER BY '.$list->sqlSort().' '.$id_field.' ASC
                                            '.$list->limit($total));
                $array_row = $db_listing->resultArray();unset($db_listing);
                break;
        }
        $total_row = count($array_row);
        $html .= $list->showHeader($total_row);
        $i = 0;
        foreach($array_row as $row){
            $i++;
            $html .= $list->start_tr($i,$row[$id_field],'class="'.$class_context_menu.' record-item" onclick="active_record('.$row[$id_field].')" data-record_id="'.$row[$id_field].'"');
            /*code something */
            $html .= '<td>'.$row['sed_name'].'</td>';
            $html .= '<td class="right">'.$row['sed_phone'].'</td>';
            $html .= $list->end_tr();
        }
        $html .= $list->showFooter();
        echo $html;
    }

}
// khoi tao doi tuong object ajax va thuc thi
$Agenajax = new AgenciesAjax();
$Agenajax->execute();
